import { Education, Experience, Resume } from './types';

export const experience: Experience[] = [
  {
    company: 'Zillow Group',
    url: 'https://www.zillowgroup.com/',
    title: 'Senior Software Engineer',
    startDate: new Date('2024-04-28T00:00:00'),
    technologies: [
      'Javascript',
      'React',
      'Python',
      'Typescript',
      'Nodejs',
      'Nextjs',
      'GraphQL',
      'Apollo',
      'AWS',
      'AWS Lambda',
      'Docker',
      'Kubernetes',
      'Tilt',
      'AWS DynamoDB',
    ],
    bullets: [
      'Lead the development of new systems to improve the purchase and rental experience.',
      'Contributed to the development of new features to improve the overall user experience.',
      'Developed and maintained BackEnd features and microservices to enhance scalability.',
      'Mentored junior developers.',
      'Performed code reviews to ensure quality standards.',
      'Optimized code to deliver the best performances possible.',
      'Analyzed points of opportunity to tackle performance issues.',
      'Proficient on development of new features.',
      'Architecture contributions to improve the overall systems.',
    ],
  },
  {
    company: 'X-Team',
    url: 'https://x-team.com/',
    title: 'Senior Software Engineer',
    startDate: new Date('2021-10-01T00:00:00'),
    endDate: new Date('2024-04-01T00:00:00'),
    technologies: [
      'Temporal',
      'vue.js',
      'Go Lang',
      'Hapi.js',
      'React',
      'AWS',
      'AWS Lambda',
      'Nodejs',
      'Postgres',
      'Docker',
      'Kubernetes',
    ],
    bullets: [
      'Developed and maintained FrontEnd and BackEnd features.',
      'Performed code reviews to ensure quality standards.',
      'Optimized code to deliver the best performances possible.',
      'Analyzed points of opportunity to tackle performance issues.',
      'Proficient on development of new features.',
      'Leading the development of new services.',
      'Architecture contributions to improve the overall systems.',
    ],
  },
  {
    client: 'GOBankingRates',
    company: 'Encora',
    url: 'https://www.encora.com/',
    title: 'Senior Software Engineer',
    startDate: new Date('2020-03-01T00:00:00'),
    endDate: new Date('2021-10-01T00:00:00'),
    technologies: [
      'PHP',
      'Python',
      'React',
      'Nextjs',
      'AWS Lambda',
      'AWS Kinesis',
      'AWS SQS',
      'AWS Dynamo',
      'AWS CloudWatch',
    ],
    bullets: [
      'Developed and maintained BackEnd features and microservices to enhance scalability.',
      'Mentored junior developers.',
      'Architecture contributions on multi-regional delivery and reliability.',
      'Refactored internal libraries following clean code principles to improve performance and maintainability.',
      'Migrated microservices from a conventional environment to a Serverless one to optimize infrastructure performance.',
      'Led the development and integration of an internal microservice that advanced data quality.',
      'Modernized a legacy codebase by migrating from PHP to JavaScript which improved functionality and standardization.',
      'Performed code reviews that ensured that the software was meeting its specifications and quality standards.',
    ],
  },
  {
    company: 'The Ksquare Group',
    client: 'Boy Scouts of America',
    title: 'Software Engineer',
    url: 'https://www.theksquaregroup.com/',
    startDate: new Date('2019-07-01T00:00:00'),
    endDate: new Date('2020-03-01T00:00:00'),
    technologies: [
      'Javascript',
      'Nodejs',
      'Hapi.js',
      'SQL Server',
      'Rest',
      'AWS',
      'jenkins',
      'Verdaccio',
    ],
    bullets: [
      "Developed and maintained the organization's core API REST endpoints to ensure proper integration and functionality.",
      'Improved microservice architecture to allow microservices to work together to operate as a monolithic service.',
      'Refactored complex SQL queries to improve application performance.',
      'Performed code reviews to improve code readability, performance, and maintainability.',
      "Analyzed log data to detect anomalies in the API's performance and promptly resolve the issues.",
      'Deployed multiple APIs from a Monorepo to optimize version control',
    ],
  },
  {
    company: 'Freelance',
    title: 'Software Engineer',
    startDate: new Date('2017-12-01T00:00:00'),
    endDate: new Date('2019-07-01T00:00:00'),
    technologies: [
      'Javascript',
      'Typescript',
      'React',
      'React Native',
      'Nodejs',
      'Docker',
      'Kubernetes',
      'GCP cloud run',
      'Mongodb Atlas',
      'Angular 7',
      'Loopback 3',
      'PostgreSQL',
      'Redis',
      'Elasticsearch',
      'AWS',
      'CI/CD',
    ],
    bullets: [
      'Worked on the entire full development lifecycle of an application to ensure a quality product from start to finish.',
    ],
  },
  {
    client: 'GE Digital',
    company: 'Lüphole',
    url: 'https://luphole.com/',
    title: 'Software Engineer',
    startDate: new Date('2015-01-01T00:00:00'),
    endDate: new Date('2017-12-01T00:00:00'),
    technologies: [
      'Javascript',
      'Nodejs',
      'Loopback 3',
      'Angular 4',
      'Typescript',
      'Mongodb',
      'Electron',
      'iOS',
      'Windows',
      'Rest',
      'AWS',
      'Elastic',
      'Cordova',
    ],
    bullets: [
      'Worked on the entire full development lifecycle of an application to ensure a quality product from start to finish.',
      'Built features that enabled the app to communicate with other iterations of the same app.',
      'Indexed large quantities of PDFs to enable a function that could search the PDF files.',
      'Developed a Desktop and Web User Interface with Angular to promote an intuitive User Experience.',
      "Integrated with GE's intranet and authorization services to optimize security.",
      'Designed the application to be compatible with Desktop and Web browsers to increase cross-platform usability.',
      'Designed the architecture of the backend, desktop and web applications.',
    ],
  },
] as const;

export const education: Education[] = [
  {
    institution: 'Centro de Enseñanza Técnica Industrial (CETI)',
    degree: 'Computer Information Technologist',
    location: 'Guadalajara, Jalisco, México',
    startDate: new Date('2012-01-01T00:00:00'),
    endDate: new Date('2016-01-01T00:00:00'),
  },
];

export const resume: Resume = {
  name: 'Germán Meza',
  description: `I am a software developer with a passion for scalable and efficient software. I enjoy building at scale, taking pictures, and traveling.`,
  email: 'iam@germanamz.com',
  country: 'México',
  website: 'https://germanamz.com',
  github: 'https://github.com/germanamz',
  linkedin: 'https://linkedin.com/in/germanamz',
  experience,
  education,
} as const;
